# Generated by Django 4.2.5 on 2023-09-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_Shelter_Model',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age_upon_outcome', models.CharField(max_length=50)),
                ('animal_id', models.CharField(max_length=50)),
                ('animal_type', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('monthyear', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('outcome_subtype', models.CharField(max_length=50)),
                ('outcome_type', models.CharField(max_length=50)),
                ('sex_upon_outcome', models.CharField(max_length=50)),
                ('location_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('location_long', models.DecimalField(decimal_places=8, max_digits=11)),
                ('age_upon_outcome_in_weeks', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
    ]
